### ISSUE TITLE
Possible bug / when sls dash deploy in function folder models are not found

### ISSUE THREAD

**Issue by mwawrusch** [HyperBrain/serverless-models-plugin#12]
I ran into this recently, when I sls dash deploy from the top level directory everything is fine but when doing so from the actual function directory it does not resolve the model.

**Comment by HyperBrain** [comment]
Did this also happen with the previous version (1.0.1)?

**Comment by mwawrusch** [comment]
Sorry for the late reply, I have too many notifications... It works in 1.0.1, looks like a regression. I will just use that one for the time being. Thanks for the great work.
