### ISSUE TITLE
updating s-project.json

### ISSUE THREAD

**Issue by carlhunterroach** [HyperBrain/serverless-models-plugin#2]
although there is generic text at serverless.com it would be nice to have a section on adding this plugin to. I guessed wrong with 'serveless-model' and realised my error. If the really-useful server less-models-plugin is one's first plugin one could over look the need to update  

In the file s-project.json add the plug to the list of plug-ins. E.g., 

> {
>   "name": "juturnaSLS",
>   "custom": {},
>   "plugins": ["serverless-models-plugin"]
> }

**Comment by HyperBrain** [comment]
Will update the README. Thank you :-)
